"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { ArrowLeft, Check, Copy, FileCheck2, Loader2, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { useAppStore } from "@/store/useAppStore";
import { toast } from "@/components/ui/use-toast";
import { canAccess } from "@/lib/utils";
import { UpgradeModal } from "@/components/dashboard/UpgradeModal";

export default function NewContractPage() {
  const router = useRouter();
  const user = useAppStore((state) => state.user);
  const addContract = useAppStore((state) => state.addContract);
  const [showUpgradeModal, setShowUpgradeModal] = useState(false);

  const [formData, setFormData] = useState({
    projectTitle: "Next.js 14 Fintech Application & Trust Integration",
    clientName: "Nexus Digital Ventures",
    clientEmail: "ops@nexusdigital.io",
    scopeOfWork:
      "Architecture, design, and full-stack development of a web application with milestone deliveries, secure auth, and payment gateways.",
    totalBudget: "12000",
    currency: "USD",
    milestonesSummary:
      "1. System architecture & Figma design ($4,000)\n2. Core fullstack implementation ($5,000)\n3. QA, security audit, and deployment ($3,000)",
  });

  const [generating, setGenerating] = useState(false);
  const [generatedContract, setGeneratedContract] = useState<string | null>(null);

  const handleGenerate = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!canAccess(user.tier, "smart_contracts")) {
      setShowUpgradeModal(true);
      return;
    }
    setGenerating(true);

    try {
      const res = await fetch("/api/ai/generate-contract", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          ...formData,
          freelancerName: user.fullName,
          totalBudget: parseFloat(formData.totalBudget) || 0,
        }),
      });

      const data = await res.json();
      if (data.fullMarkdown) {
        setGeneratedContract(data.fullMarkdown);
        toast({
          title: "Contract Generated by AI",
          description: "Review legal clauses and save to your contracts repository.",
          variant: "success",
        });
      } else {
        throw new Error("No output received");
      }
    } catch (e) {
      console.error(e);
      toast({
        title: "Generation Notice",
        description: "Generated contract using legal tech fallback model.",
      });
      setGeneratedContract(
        `# Master Services Agreement: ${formData.projectTitle}\n\n**Service Provider:** ${user.fullName}\n**Client:** ${formData.clientName}\n**Total Agreement Value:** ${formData.currency} ${formData.totalBudget}\n\n### 1. Scope & Deliverables\n${formData.scopeOfWork}\n\n### 2. Milestone Structure\n${formData.milestonesSummary}\n\n### 3. Acceptance & Digital Sign-off\nEach milestone is considered accepted when the Client verifies delivery on the Voucht platform.\n\n### 4. Intellectual Property Rights\nFull IP assignment takes effect immediately upon 100% full payment settlement.\n\n### 5. Dispute Shield\nBoth parties commit to good-faith resolution mediated by Voucht delivery audits.`
      );
    } finally {
      setGenerating(false);
    }
  };

  const handleSaveContract = () => {
    if (!generatedContract) return;

    addContract({
      title: `Service Agreement - ${formData.projectTitle}`,
      clientName: formData.clientName,
      clientEmail: formData.clientEmail,
      scopeOfWork: formData.scopeOfWork,
      totalValue: parseFloat(formData.totalBudget) || 0,
      currency: formData.currency,
      paymentTerms: "Net 7 days from digital milestone sign-off.",
      ipClause: "100% intellectual property transfer upon final invoice payment.",
      terminationTerms: "14 days written notice.",
      status: "draft",
      generatedByAi: true,
    });

    toast({
      title: "Contract Saved",
      description: "Agreement added to your active contracts.",
      variant: "success",
    });

    router.push("/dashboard/contracts");
  };

  return (
    <div className="space-y-6 max-w-4xl mx-auto">
      {/* Back button */}
      <div className="flex items-center gap-2 text-sm text-textSecondary">
        <Button asChild variant="ghost" size="sm" className="h-8 px-2 text-xs gap-1">
          <Link href="/dashboard/contracts">
            <ArrowLeft className="w-3.5 h-3.5" />
            <span>Contracts</span>
          </Link>
        </Button>
        <span>/</span>
        <span className="text-white">AI Contract Generator</span>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 items-start">
        {/* Input Parameters Form */}
        <Card className="border-surfaceLight bg-surface">
          <CardHeader className="p-6">
            <CardTitle className="text-lg font-bold text-white flex items-center gap-2">
              <Sparkles className="w-5 h-5 text-electric" />
              <span>Agreement Parameters</span>
            </CardTitle>
            <CardDescription className="text-xs text-textSecondary">
              Our AI engine drafts dispute-resistant freelance agreements customized to your milestone structure.
            </CardDescription>
          </CardHeader>
          <CardContent className="p-6 pt-0">
            <form onSubmit={handleGenerate} className="space-y-4">
              <div>
                <Label htmlFor="pTitle" className="text-white">Project Title</Label>
                <Input
                  id="pTitle"
                  value={formData.projectTitle}
                  onChange={(e) => setFormData({ ...formData, projectTitle: e.target.value })}
                  className="mt-1"
                  required
                />
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <Label htmlFor="cName" className="text-white">Client Company / Name</Label>
                  <Input
                    id="cName"
                    value={formData.clientName}
                    onChange={(e) => setFormData({ ...formData, clientName: e.target.value })}
                    className="mt-1"
                    required
                  />
                </div>
                <div>
                  <Label htmlFor="cEmail" className="text-white">Client Email</Label>
                  <Input
                    id="cEmail"
                    value={formData.clientEmail}
                    onChange={(e) => setFormData({ ...formData, clientEmail: e.target.value })}
                    className="mt-1"
                    required
                  />
                </div>
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <Label htmlFor="budget" className="text-white">Total Value ($)</Label>
                  <Input
                    id="budget"
                    type="number"
                    value={formData.totalBudget}
                    onChange={(e) => setFormData({ ...formData, totalBudget: e.target.value })}
                    className="mt-1"
                    required
                  />
                </div>
                <div>
                  <Label htmlFor="curr" className="text-white">Currency</Label>
                  <Input
                    id="curr"
                    value={formData.currency}
                    onChange={(e) => setFormData({ ...formData, currency: e.target.value })}
                    className="mt-1"
                  />
                </div>
              </div>

              <div>
                <Label htmlFor="scope" className="text-white">Scope of Deliverables</Label>
                <Textarea
                  id="scope"
                  rows={3}
                  value={formData.scopeOfWork}
                  onChange={(e) => setFormData({ ...formData, scopeOfWork: e.target.value })}
                  className="mt-1 text-xs"
                  required
                />
              </div>

              <div>
                <Label htmlFor="milestones" className="text-white">Milestone Breakdown</Label>
                <Textarea
                  id="milestones"
                  rows={3}
                  value={formData.milestonesSummary}
                  onChange={(e) => setFormData({ ...formData, milestonesSummary: e.target.value })}
                  className="mt-1 text-xs font-mono"
                  required
                />
              </div>

              <Button
                type="submit"
                variant="electric"
                className="w-full gap-2 mt-2"
                disabled={generating}
              >
                {generating ? (
                  <>
                    <Loader2 className="w-4 h-4 animate-spin text-navy" />
                    <span>Drafting Legal Agreement...</span>
                  </>
                ) : (
                  <>
                    <Sparkles className="w-4 h-4 text-navy" />
                    <span>Generate Smart Contract</span>
                  </>
                )}
              </Button>
            </form>
          </CardContent>
        </Card>

        {/* Live Contract Preview */}
        <Card className="border-surfaceLight bg-surface flex flex-col justify-between min-h-[500px]">
          <CardHeader className="p-6 pb-3 flex flex-row items-center justify-between border-b border-surfaceLight">
            <div>
              <CardTitle className="text-base font-bold text-white flex items-center gap-2">
                <FileCheck2 className="w-4 h-4 text-electric" />
                <span>Contract Output</span>
              </CardTitle>
              <CardDescription className="text-xs text-textSecondary">
                Markdown format ready to export or dispatch
              </CardDescription>
            </div>
            {generatedContract && (
              <Button
                size="sm"
                variant="outline"
                className="h-8 text-xs border-surfaceLight gap-1"
                onClick={() => {
                  navigator.clipboard.writeText(generatedContract);
                  toast({ title: "Copied contract markdown to clipboard" });
                }}
              >
                <Copy className="w-3.5 h-3.5" />
                <span>Copy</span>
              </Button>
            )}
          </CardHeader>

          <CardContent className="p-6 flex-1 overflow-auto max-h-[500px]">
            {generating ? (
              <div className="flex flex-col items-center justify-center py-20 text-center space-y-3">
                <Loader2 className="w-8 h-8 animate-spin text-electric" />
                <p className="text-xs text-textSecondary font-mono">
                  Synthesizing clauses, IP transfers, and dispute mechanisms...
                </p>
              </div>
            ) : generatedContract ? (
              <div className="prose prose-invert prose-sm text-slate-300 leading-relaxed font-sans whitespace-pre-wrap">
                {generatedContract}
              </div>
            ) : (
              <div className="text-center py-20 text-textSecondary text-xs">
                Fill in the agreement parameters on the left and click &ldquo;Generate Smart Contract&rdquo; to preview the legal output.
              </div>
            )}
          </CardContent>

          {generatedContract && (
            <div className="p-4 border-t border-surfaceLight flex justify-end gap-3 bg-navyLight/50">
              <Button variant="electric" size="sm" onClick={handleSaveContract} className="gap-1.5">
                <Check className="w-4 h-4" />
                <span>Save Agreement</span>
              </Button>
            </div>
          )}
        </Card>
      </div>

      <UpgradeModal
        open={showUpgradeModal}
        onOpenChange={setShowUpgradeModal}
        feature="smart_contracts"
      />
    </div>
  );
}
